package yoyo.ui;

import yoyo.command.Command;
import yoyo.command.Parser;
import yoyo.exception.YoyoException;

import yoyo.task.Task;
import yoyo.task.TaskFile;
import yoyo.task.Tasks;

import java.util.Scanner;
import java.util.List;

/**
 * The {@code Chatbot} class manages the main logic of the application.
 * It coordinates interaction between the user interface, the task parser,
 * and the task storage system.
 */
public class Chatbot {
    /** The horizontal line used as a separator in the console interface. */
    private static final String HORIZONTAL_LINE = "-----------------------------";

    /** The collection of tasks currently managed by the chatbot. */
    private Tasks tasks = new Tasks();

    /** The file storage handler for persisting tasks. */
    private TaskFile taskfile = new TaskFile();

    /** The parser used to interpret user commands. */
    private Parser parser = new Parser();

    /** The command executor for performing task-related operations. */
    private Command command = new Command();

    /**
     * Initializes a new {@code Chatbot} instance.
     * This constructor triggers the loading of existing tasks from the storage file.
     */
    public Chatbot() {
        readTask();
    }

    /**
     * Starts the interactive command-line interface for the chatbot.
     * This method handles the main input loop, reading user commands from {@code System.in}
     * and printing responses to {@code System.out} until the user types "bye".
     */
    public void chat() {
        Scanner sc = new Scanner(System.in);

        printHorizonalLine();
        System.out.println("Hello! I'm Yoyo.");
        System.out.println("What can I do for you?");
        printHorizonalLine();
        String input = sc.nextLine();

        while (!input.equals("bye")) {
            printHorizonalLine();

            try {
                Task task = this.parser.parse(input, tasks);
                String response = this.command.execute(tasks, task);
                System.out.println(response);
                saveTask();
            } catch (YoyoException e) {
                System.out.println(e.getMessage());
            } finally {
                printHorizonalLine();
                input = sc.nextLine();
            }
        }

        printHorizonalLine();
        System.out.println("Bye. Hope to see you again!\nThe app will close in 5 seconds.");
        printHorizonalLine();
    }

    /**
     * Processes a single user input and returns the chatbot's response.
     * This method is intended for use with graphical user interfaces.
     *
     * @param input The raw input string from the user.
     * @return The response string generated by the chatbot, or an error message if the input is invalid.
     */
    public String getResponse(String input) {
        if (input.equals("bye")) {
            return "Bye. Hope to see you again!\nThe app will close in 5 seconds.";
        }
        try {
            Task task = this.parser.parse(input, tasks);
            String response = this.command.execute(tasks, task);
            saveTask();
            return response;
        } catch (YoyoException e) {
            return e.getMessage();
        }
    }

    /**
     * Prints a horizontal line separator to the console.
     */
    private void printHorizonalLine() {
        System.out.println(Chatbot.HORIZONTAL_LINE);
    }

    /**
     * Persists the current list of tasks to the storage file.
     * The task information is formatted by the {@code Tasks} class before saving.
     */
    private void saveTask() {
        this.taskfile.writeList(tasks.getFileOutput());
    }

    /**
     * Loads tasks from the storage file into the {@code Tasks} collection.
     * The input file is read as a list of strings, each representing a task
     * in its serialized format.
     */
    private void readTask() {
        List<String> list = this.taskfile.readList();
        for (String s : list) {
            this.tasks.storeTask(s.split(" \\| "));
        }
    }
}
